### ISSUE TITLE
Add some kind-of 'display' command line argument

### ISSUE THREAD

**Issue by coppolat1** [coppolat1/bumpCversion#8]
Perhaps add something like: `--display-versions` that would go into the configuration and get the current version of all components and all files. Then print the versions out in a table/list.

**Comment by travisrecupero** [comment]
We enforce that all versions are the same across multiple files. If this check fails, the program doesn't run and will output the different versions found.  -> https://github.com/coppolat1/bumpCversion/pull/6

**Comment by travisrecupero** [comment]
I dont think #6 was added to a tag. That might've been the issue. I was going to wait to create it until the pytest test cases were done, but let me know if you want me to do it sooner.

**Comment by coppolat1** [comment]
Yes, I'm aware of that. What I am looking for is like a high-level printout the current versions of *all* the components in the config file. For example:

```
bumpCversion.py /.bump.cfg --display-versions

naibrd:       3.4.1
naibsp:       1.0.1
someOtherLib: 2.3.1
continued...
```

Let me know if that makes sense.

**Comment by travisrecupero** [comment]
So each components respective files will have the same version number, but each component can have different version numbers?

**Comment by coppolat1** [comment]
Yes, that is already the case (in the repo we're using this tool in). Each 'component' is separate from one-another in regards to version number. 

What I'm suggesting in this issue is we should add a CLI switch that just displays the versions in each component of the config file.

**Comment by travisrecupero** [comment]
How does this output look? :
![image](https://user-images.githubusercontent.com/31936622/159341031-e8820ee7-2d4f-492b-8762-79891fa1bccd.png)

The only problem is that we **require** some args (we only _need_ `--config-file` here). Which is also why we see "Using component" in the beginning of the output, because we are using `--component naibsp` in our command (not _needed_).
