### ISSUE TITLE
Preserve Doxyfile Spaces

### ISSUE THREAD

**Issue by coppolat1** [coppolat1/bumpCversion#9]
I noticed while using `bumpCversion` for an SSK release that we don't preserve the spaces to the left of the equal sign.

Modifying the Doxyfile regex, we should be able to add a capture group to capture that data and inject it back into the file post-bump. This is pretty low priority.

Example of what happened:

``` patch
Index: Doxyfile_naibrd
===================================================================
--- Doxyfile_naibrd	(revision 9293)
+++ Doxyfile_naibrd	(working copy)
@@ -38,7 +38,7 @@
 # could be handy for archiving the generated documentation or if some version
 # control system is used.
 
-PROJECT_NUMBER         = 2.13.0
+PROJECT_NUMBER = 2.14.0
 
 # Using the PROJECT_BRIEF tag one can provide an optional one line description
 # for a project that appears at the top of each page and should give viewer a

```

**Comment by travisrecupero** [comment]
I dont think https://github.com/coppolat1/bumpCversion/pull/6 was added to a tag. That might've been the issue. I was going to wait to create it until the pytest test cases were done, but let me know if you want me to do it sooner.

**Comment by coppolat1** [comment]
No rush on either of the two issues I added today. Just logging down some thoughts as I was using the tool :-) I'm not sure what you mean about the tag.

**Comment by travisrecupero** [comment]
If this output was from a run from the program on the svn repo, then it might've not been using code from gits main branch. Svn could have been using [0.7.0](https://github.com/coppolat1/bumpCversion/releases/tag/v0.7.0) or earlier.

**Comment by coppolat1** [comment]
I see what you mean. When I created tag [v0.8.0](https://github.com/coppolat1/bumpCversion/releases/tag/v0.8.0), I also update the SVN repo.

**Comment by travisrecupero** [comment]
Fixed in https://github.com/coppolat1/bumpCversion/commit/9eb5f2a9329a6754a2c1c13019f91408d95b4078

Closing Issue
